GET http://localhost:9898/users

###

GET http://localhost:9898/users/60bb04e76d272040dc9cf974

###

# Signing a user up
POST http://localhost:9898/users
Content-Type: application/json

{
  "username": "as",
  "password": "a"
}

###

# Logging a user in
POST http://localhost:9898/users/login
Content-Type: application/json

{
  "username": "a",
  "password": "a"
}

###
DELETE http://localhost:9898/users